# Generated by Django 3.1.1 on 2020-10-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0002_auto_20201013_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_kits',
            name='user',
        ),
        migrations.CreateModel(
            name='UsersTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_kits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.test_kits')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
