# Generated by Django 3.1.1 on 2020-10-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20201013_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.test'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='right_answer',
            field=models.BooleanField(blank=True, default=False, verbose_name='Правильный ответ'),
        ),
    ]
