# Generated by Django 3.1.1 on 2020-10-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0005_auto_20201013_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstest',
            name='usersanswer',
            field=models.ManyToManyField(null=True, to='Test.Answer'),
        ),
        migrations.AlterField(
            model_name='userstest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
