# Generated by Django 3.1.1 on 2020-10-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_auto_20201013_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефоный номер'),
        ),
    ]
