# Generated by Django 3.1.1 on 2020-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_auto_20201013_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='test_kits',
        ),
        migrations.AlterField(
            model_name='userstest',
            name='usersanswer',
            field=models.ManyToManyField(to='Test.Answer'),
        ),
    ]
