# Generated by Django 3.1.1 on 2020-10-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_auto_20201020_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstest',
            name='test_kits',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.test'),
        ),
    ]
