# Generated by Django 3.1.1 on 2020-10-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_auto_20201025_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstest',
            name='usersanswer',
        ),
        migrations.AddField(
            model_name='userstest',
            name='usersanswer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.answer'),
        ),
    ]
