# Generated by Django 3.1.1 on 2020-11-14 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0012_auto_20201030_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_tests', models.IntegerField()),
                ('right_tests', models.IntegerField()),
                ('test_kits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test_kits')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
